### ISSUE TITLE
Fix Codacy coverage report

### ISSUE THREAD

**Issue by hajduakos** [ftsrg/theta#138]
Linux builds are failing due to some Codacy coverage reporting issues.

**Comment by hajduakos** [comment]
Seems like it's working on master. But then why did it fail for https://github.com/ftsrg/theta/pull/137? Is it because it was a PR from a separate fork?

**Comment by radl97** [comment]
This is due to a separate fork I think. It seems logical, because 1) anyone can fork a public repo 2) Actions (and secrets) could be using external (paid) resources.

It is the same with @LendvaiDenes 's PR. (I was talking to him, hence the related PR).

Main issue, I think, is that forks do not get the codacy secrets of the main project.

(I'll reopen the issue, I do not fully understand what it means that it is closed. I think this issue is missing a conclusion. Is this a wontfix, or it is solved as the main project (i.e. not a fork) does not have the issue? )

**Comment by hajduakos** [comment]
Yeah, I thought that this is a wontfix, but I agree that it would be nicer to fix so that people have meaningful build results on forks. I know that we can skip certain steps based on branch names, is it also possible to do based on forks? https://github.community/t/how-to-detect-a-pull-request-from-a-fork/18363 seems to give some suggestions
