### ISSUE TITLE
[CFA] Floating point type syntax shadows bitvector `extract` expression

### ISSUE THREAD

**Issue by leventeBajczi** [ftsrg/theta#148]
Currently, both the type declaration of floating point variables and the `extract` expression of bitvectors use the `[FROM:TO]` notion, but for different purposes, with separate token types. This makes `extract` operations unparsable. 
Currently, some of the tests regarding CFA-s are disabled for this purpose, which must have been a quick fix, but somehow stayed in the current code on master. To my knowledge, this problem only appears in the CFA grammar [CfaDsl.g4](https://github.com/ftsrg/theta/blob/master/subprojects/cfa/cfa/src/main/antlr/CfaDsl.g4).

**Comment by leventeBajczi** [comment]
@as3810t if you have some time, could you take a look? What should be the solution (what syntax could be better, and for which expression)?

**Comment by as3810t** [comment]
Personally, I chose the `[FROM:TO]` syntax for the bitvector extract expression because of Python: in a way, it extracts a list of bits from a list of bits. Also, this syntax is integrated with and used by PLCverif, so I would not change it unless absolutely necessary.

As for the floating point declaration, how about `[SIG, EXP]`? Conceptually, these declarations should have two parameters, so it is given in a two-element list. On the other hand, bitvectors require a single parameter, so they are given a one-element list (`[SIZE]`).
