### ISSUE TITLE
Find out how to do pre-runs (somehow via coveriteam)

### ISSUE THREAD

**Issue by leventeBajczi** [ftsrg/theta#216]

**Comment by leventeBajczi** [comment]
Hey, the deadline for this task has already passed. Is there any update on this issue @AdamZsofi?

**Comment by AdamZsofi** [comment]
This year we are supposed to upload to zenodo and open a merge request with the DOI. No one seems to have done this yet and some things are not clear.

I'll try to get some more information, but otherwise I suggest we wait and try to get everything else ready, so that we can easily upload the tool when needed.

**Comment by leventeBajczi** [comment]
I think, for this year, we will not use the coveriteam service for own preruns. Maybe next year :)
