### ISSUE TITLE
Adjust Codacy settings to match the coding style

### ISSUE THREAD

**Issue by as3810t** [ftsrg/theta#83]
Right now Codacy checks every pull request. However, Codacy's settings do not always match the coding conventions that Theta follows.

For example, the message below is a common error, that is reported for all creational static methods in the `<Type>Exprs` static classes:
```
The static method name 'Add' doesn't match '[a-z][a-zA-Z0-9]*'
```

As a result, as of now all the pull requests are merged with failing checks, disregarding the fact, whether they do or do not follow the conventions of Theta. This way, bogus errors might shadow actual problems with the code, and thus code with lower than standard quality might be merged to master.

**Comment by hajduakos** [comment]
Agreed. I'm currently in progress of tuning these settings. However, sometimes it is difficult because of the granularity of the rules. For example, to silence warnings about methods starting with uppercase, the whole rule on checking method naming conventions must be turned off. I will play around it. Also, if you feel like it, you can take a look at the rules and give suggestions what to disable or enable.
