### ISSUE TITLE
Support for reset in Z3 solver

### ISSUE THREAD

**Issue by vincemolnar** [ftsrg/theta#92]
Message is null.
Solver was Z3.

**Comment by hajduakos** [comment]
We should either implement it, or give a more informative error message (e.g., "Z3 solver does not support reset, please use push/pop"). I started implementing it to see if it works: c4e3ad0a278dfe3c8866d3c6723443448d5e90e0

@as3810t what do you think? It is not as trivial as it might seem. Basically, in the `Z3Solver`, we have:
- `com.microsoft.z3.Solver`: this has a `reset` method, we can call it.
- `Stack<Expr<BoolType>> assertions`: we can clear this.
- `Map<String, Expr<BoolType>> assumptions`: we can clear this.
- `Z3SymbolTable`: we can clear this.
- `Z3TransformationManager`: I think we also have to clear caches here, because if the symbol table is cleared, the cached expressions might be invalid. I haven't done this yet, but the simple test works.
- `Z3TermTransformer`: this is the back-transformation, but there does not seem to be any caching so I think we can just leave this.
- `com.microsoft.z3.Context`: I have no idea what to do with this.

**Comment by hajduakos** [comment]
Update: in b35c5590c757e76689f2d3ada35fc275792c48c3 I added reset to 2 members of `Z3TransformationManager`: `Z3TypeTransformer` and `Z3ExprTransformer`. As far as I see, `Z3DeclTransformer` does not need reset.

**Comment by hajduakos** [comment]
I was also thinking about completely removing it from the interface, but if it seems to work, we can leave it there for quick prototyping. I added some comments that push/pop should be preferred.

**Comment by as3810t** [comment]
As far I can see, the Solver API in Z3 has a `reset` method: https://github.com/Z3Prover/z3/blob/master/src/api/java/Solver.java#L105

So it should not be difficult to reset it through z3Solver: https://github.com/ftsrg/theta/blob/c48087ae29b63887edcc2d16482a8925faf55143/subprojects/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3Solver.java#L57

**Comment by hajduakos** [comment]
Is that enough? Because in [Z3Solver](https://github.com/ftsrg/theta/blob/solver-reset/subprojects/solver-z3/src/main/java/hu/bme/mit/theta/solver/z3/Z3Solver.java) we have additional stuff, as outlined in my previous comments.

**Comment by as3810t** [comment]
Yes of course, what you described is needed :) My earlier remark was for: 
> - com.microsoft.z3.Context: I have no idea what to do with this.

**Comment by hajduakos** [comment]
I see. I'll create a PR then
